services:
  logging-service:
    image: trubudget/logging-service:${TAG}
    environment:
      LOGGER_PORT: ${LOGGING_SERVICE_PORT}
      API_HOST: ${API_HOST}
      API_PORT: ${API_PORT}
      LOG_LEVEL: ${LOGGING_SERVICE_LOG_LEVEL}
      LOGGING_SERVICE_CACHE_DURATION: ${LOGGING_SERVICE_CACHE_DURATION}
      NODE_ENV: ${ENVIRONMENT}
    ports:
      - "${LOGGING_SERVICE_PORT}:${LOGGING_SERVICE_PORT}"

  frontend:
    environment:
      REACT_APP_LOGGING: true
      REACT_APP_LOGGING_SERVICE_HOST: ${LOGGING_SERVICE_HOST}
      REACT_APP_LOGGING_SERVICE_PORT: ${LOGGING_SERVICE_PORT}
      REACT_APP_LOGGING_SERVICE_HOST_SSL: ${LOGGING_SERVICE_HOST_SSL}
      REACT_APP_LOGGING_PUSH_INTERVAL: ${LOGGING_PUSH_INTERVAL}
