services:
  api:
    image: trubudget/api:${TAG}
    environment:
      PORT: ${API_PORT}
      ORGANIZATION: ${ORGANIZATION}
      ORGANIZATION_VAULT_SECRET: ${ORGANIZATION_VAULT_SECRET}
      RPC_HOST: ${MULTICHAIN_RPC_HOST}
      RPC_PORT: ${MULTICHAIN_RPC_PORT}
      RPC_USER: ${MULTICHAIN_RPC_USER}
      ROOT_SECRET: ${ROOT_SECRET}
      RPC_PASSWORD: ${MULTICHAIN_RPC_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SIGNING_METHOD: ${SIGNING_METHOD}
      ENCRYPTION_PASSWORD: ${ENCRYPTION_PASSWORD}
      NODE_ENV: ${ENVIRONMENT}
      ACCESS_CONTROL_ALLOW_ORIGIN: ${API_ACCESS_CONTROL_ALLOW_ORIGIN}
      CI_COMMIT_SHA: ${CI_COMMIT_SHA}
      BUILDTIMESTAMP: ${BUILDTIMESTAMP}
      LOG_LEVEL: ${API_LOG_LEVEL}
      PRETTY_PRINT: ${PRETTY_PRINT}
    # depends_on:
    #   - blockchain
    # networks:
    #   mynetwork:
    #     ipv4_address: 172.20.0.4
    ports:
      - "${API_PORT}:${API_PORT}"
